---
title: "homework-03"
author: "Mila Matich"
date: 2026-05-28
format: pdf
---

# Part 1. Homework Set Up

```{r}
#| label: loading-in-packages-and-data
#| message: FALSE


# loading in packages
library(tidyverse) # loading in tidyverse 
library(janitor) # loading in janitor 
library(readxl) # loading in readxl

# reading in and storing data as object "kelp"
kelp <- read_csv("data/temp-kelp.csv") # data/ in order to direct the file path 
# reading in and storing personal data as object "personal"
personal <- read_csv("") # data/ in order to direct the file path 
```

# Part 2. Problems 

## Problem 1. Giant kelp fronds

### a. An appropriate test

In our study, we are trying to measure the strength of the relationship between two variables (ocean temperature and giant kelp frond elongation rate). In order to test the strength of this relationship, we should use a Pearson’s product-moment correlation and a Spearman’s rank correlation. Pearson's correlation test is the parametric version of the test, while Spearman's rank correlation is the non-parametric version that measures the correlation between ranks (rather than continuous variables).

### b. Create a visualization

### c. Check your assumptions and run your test

### d. Results communication

### e. Test implications

### f. f. Double check your own work.

## Problem 2. Personal data

### a. Updating your visualizations

### b. Captions

## Problem 3. Affective visualization

### a. Describe in words what an affective visualization could look like for your personal data (3-5 sentences).

### b. Create a sketch (on paper) of your idea.

### c. Make a draft of your visualization.

### d. Write an artist statement.

### e. Prep your materials to share in class.

## Problem 4. Statistical critique

### a. Revisit and summarize

### b. Visual clarity

### c. Aesthetic clarity

### d. Recommendations






